- name: install nginx
  yum:
    use_backend: yum
    name:
      - nginx
    state: present
    update_cache: yes
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes
  
- name: stop firewalld
  service:
    name: firewalld
    state: stoped
  become: yes

- name: index
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html

